apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Release.Namespace }} # injected by Helm from the ArgoCD destination namespace
spec:
  accessModes:
    - ReadWriteOnce  # only one node can mount this at a time (fine for standalone MinIO)
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
