extends: default
rules:
  line-length:
    max: 150
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
ignore: |
  services/*/application/templates/
  secrets/
