apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
            - containerPort: {{ .Values.service.nativePort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse  # ClickHouse data directory
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: clickhouse-pvc
