apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: workspace
              mountPath: /opt/cloudbeaver/workspace  # persists JDBC connections and user preferences
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: cloudbeaver-pvc
