# helm/minio/values.yaml
mode: standalone

auth:
  existingSecret: minio-credentials
  existingSecretAccessKeyIDKey: root-user
  existingSecretSecretAccessKeyKey: root-password

defaultBuckets: "bronze,silver,gold"

persistence:
  enabled: true
  storageClass: local-path
  size: 20Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
