---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-credentials
  namespace: local-datalake
spec:
  encryptedData:
    root-password: AgAJqQMftQpU1tlTpp8uYMP9e6FaHb/c4pXkD3a4vLzL1GbpFhLhqcmaF6fJzfnoRnq5Qt4uRrbaVDMe55nqp9txxn925yr73bYFHtH3ER/5AS6HoOrUkuCdqLwYTBFUtdzxXIAnRA4xIrtYkJoywSzqw/YWMlKzzGdyoPcnNCt2CLJSCoazooGp23vRupN0kj56RQksGT8q/tgmBL+EITNRdq0W1G3v8t/KHhC6/hd28p7CgJ+0FVB3SOA5j7jwWSy9ydtnnP/eTet4LQXBocW24Z9+4q7tjz7lFJCC7ECe4MneSX6sztS+peC2Im2hsYZip2AECf0D5rQK6J7yNad4FnV4uSTYQuDfYYZsSn71N9RU3NacCeQy1TJCQCZNAhlWfXMVH4cGcRaJaYeikemYkunkJEHznhHmu4W6Y8edbX4O4TjLdubpSoBf+a124xYXwdke2vcXD61k+dmZwDEAd4bb3Pnw1vB5z3CL9xZEi5RtOAxudgcgQk4pI5yFGXezdvOZUODE3XpNe1ZUiKJ4zmYzCeQxm+QNIyOi1S1bQF2r7jocp+QJXEdC/nw7vg6s9EQRyYxrOh/Fbn9oNirJFil3LzGgJKwasHNYcO6TUQW7+u9gOp7tPxG2e6Skwob+MLaHSfFE+7m1hNQ7yWSU4APkktC5bCcTpNDRGAINpZmzAta9elYg5TDOzXc6CVjNOVM4gkBER2GOfxe1
    root-user: AgCJP8QRcLLiwFjbhhIeD/3geu9mN/Q1guaQpnVxEux7hrtmL4fUMHzZT5pw3oWde8FpFD5ee7BelwI9R7lboEK9YyuLE1fw5fOCUmu3ESHaRIV5C58pGFk9hpB1VG3SFiPMUujgtGZd1Pi342FKm6Y3BGFs239DrRhCM1WJcqd5MhFy/lsgT/WvrA0djOjAozYPWyTXOO8D+XaYKeBCgXyeq9pFm2is5s7/MXMbAoMO0YZPWQsPt9iDzKQY9kkl85TcZU9b72eTe/iRYsT0qcaHgnLjNXcfxDF5ET+JqO+G3HaE6o4qHGI/szOLZ9RgtcsW5FVLB29PwCMsE0goQkJgB7AuGe20FCSg+RnhlZKoGYmp4QSqRFZSpIVMq9iEljxXFRJVPD5Ac3a5mbWvwHbcu0rDx89xxICWS++FJEJY/xPOzk3N1H+TZBzQ1X2NkjcQXHOn9swkFFUGvZh8Df3b1YR4/ziCwgV7irYwg0Aly1H19DIE1QaCnAnblMZk5/sU6kcDIk2HhJnN2RIKdn0kuFWjJpKjJHPW6RiEXXr59kgcdlVXPM+OKIbkWfaTlI4EVylrXRsuGtt94xjjLvlF51rJuFdhy2vXDthCueBfbHmaFli4XWhWXd8oGt8q+fMejyClOgkq8ETap5SPpkUf5cHXRJmHB9wBdTtyZGg8ApXtXwSiNG7ZNtd64uLLf0gJlTwr+vkKVwoF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-credentials
      namespace: local-datalake
