---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-credentials
  namespace: local-datalake
spec:
  encryptedData:
    root-password: AgCKF8xlyJVJsiHlbRop70HvS7ZCsHEImzPnCOXGnI4g0nrJ2DiE83vCb93B/LGcTauuckI208dzU4XHQQkMuwlCLXWcdVhQ40a7Z01/67im9LYwYgXPrlEotdNcVWhoRsGcZT+oKluXqb3pFVTa5EMl384z0BC3YIY9NRrqVAOrJn/XeJYzDKeSPwWKJEI+nBBvC1kNqs6rWCVlPJ2sT3tmjiH5xHUEY/PLpk6jSgpVH/hbwVPn9e3iaIrpB/dyuSgmjlDRwv1u/UlajI5Extq54nlPjQpjEUBZxoeIoOvCttuzLuSA4eyUvVMPJsV5ZhEc0dMZtttNJ+m6Pg5diVbTrYLav9dzhsPxEt00+JUVuwEFnVm8UNRiwRqmpoq+sLo5aQ7X916Lg7FdsZI1hOEjvOPDxIXaoe+L9M7QemhBZIqXBhhsQIRHS59XegrfFqZAFq3fRSr8kLM/sCnPvOsp+Mo2ykRgyfzMho2PyCYIia6VRUldYuMQlzBPrqjY+wMgX3ThzLf3xzTk7e0dFlEM0gxBKXKMCKYmhWpG7SDgz3ugD0Pj3JJmrOQjiQLsVowkCqbecG/rRMah2MU9BmQ6KkR8hqYyGs+CnICxuW1WYeaHy/3dln396et+VArJQz0DWnrFovjVSpee+1hVbKNG/yCgC3s+s+Mqvw4MvCO2HNVETuPP+V8A3wrpjNHP6+SgBOWgqpmROxFGyICJ
    root-user: AgCzoQ4k+uPyI+ORGL+zRhZqiv8RsVh5CK8Z19972bp3R6eDYhvyuPqSB93Lh9G6U8xOE7WTLA2dQP9hML8GFXD1+rWAgdremklqY/EZSHPcX/KOybe/tjNK4E20oAO/3fDQvZzn2uKbhh9mMXbOSb3S7TfIB0Ar4rl36rJCLWOdqFcKPHRhtwS3CNZvnH16fZPSWgxdvdiuPQpdSfBRGOxcIBbrjYyn8H2ic9yGamrUWhm8Kljjp7Qko8NGWV/LK5OD9oLK+pE0ZlVQkoPKGTpwQVpWRFLY//eYtjhzh/tZpU6XTKvinb+FJ+CzoC30Z1v2COUXfI40gq1vJkXRoPDSeGuBhd0toJQ07QFAqXz0rPHIvhcY3W3K0CHoaaQXdOYkgk1PRerakyK7PU2X5oSMmuI+MwU6SdTZfcu8uG6Mtu27ljNKjWBoG9wMSWOqZAtJlYCfAB9gkAtD4N5Q5+sDB4lJ4yyqM129AsYZEEzn11XRcwVVH88OCP3fN1YvCunOPyzW7t0RKi1K8ZVUmAcOrCIueKj5WalY6LgZkpykwhA67p/q1oXXsbGoLymlh2F5/OIqeXM7kryihg/GbYRJ7hz1/X5zwOpZ0zZf/B59o4S/7xNCDAa/zPeu6uCqxUSeqaOuRaQdYedBwbf/Eg9uF9NwhGCAUa3Vc8iWIToiGSvR1kb2w/BhWPHqvzlhQc3M7271nU5Yxgk5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-credentials
      namespace: local-datalake
