---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-credentials
  namespace: phase-1
spec:
  encryptedData:
    root-password: AgCrUx+Doqc67z8a86WfxMUYMEmMxM5JCxH5anvPFpjVd6hpl995S5MqZ09BiMzerS0ulAGR98pXZeTiXNF1vykufzUA38VJ+WnGAjjCJCgd3pvu+oKxOU6jyB/YnI5ImzHW7MBdorbIOn0EE5AIBQqP4ywyM6FdLMxQ2RxmvIeJkTGaJBnCNgvOVHweGmrlhjSDj/G70L8vFRxyarzopCUsKhpIpT02GAJYwjjYYp3wm6B3bRFrt+9ddM/XEZLN5Milmqqt581KwZQhx3JFO2gqETdcQd6ZL8DOHv1p7+qp6VUz1pPYDbD5nFHr/3uH0vdcoOJhusvTxeC3gS1eFXLlBFsWEd/ufeQ4gCBpKETbySF0DheL7MWRMrGDZdgvohkGwEG7Y8dTHn7sAKxlSE3kHkW5J/6YtkkFfOqrYtZ0he2wy58dKRsIW83gk/bt3SKb/NLNZf5mcSfqVlTZNIoZqm2ct2qxO8yb8JpXg/4ZEboowQcvBNrcGUf1ao/5mnPI8pMxgIYlsz6QbTazu/RRh1wPzeJqBszwlj0B+Gw+P2wxtdZxE4J13Yy8rpdYaOoMheFJKy3sCGbgR3WRzop4nNOF9ilvffx9l2bBKFf7IEmLEz2Uio2V3pyNOf4zBhiwccLWhiDe3fyAmzNYG8anoSDXyRjqost520So05ijNOrc7R5GvHw/iNoMQf7T9xevSd55tx5EQDmkmM/2
    root-user: AgAGQJRbwiSsZzBg2YtYVG0T6VAZv9O67Kb27UCz9MkO9KuMAfixLAxgY++HKwlk04lLHklAxdZ75lfYw0RyiWAqyHpr8LLE0AMdw8gMmQVQbyd1oqb7zxRMfo99Tpu4Vls29j6hfkcN7e8KUl5Yxwz9X1hlHH5GEsV1NoRjzb5J4OT+DK+h6CM0ZWb5OYY7wH6bcpZM+J/dV+UYlRnrsciEuLWKwJmRCL33UmXnLUz0aFuDPRZd4MIffl1VF3cflHM5xftzpV3iYlKex+eFlh0WJ+G03HacCHTz46IAEDO7HMuRtXx8uamYWQ/o4FEM6usEghLajmKU8pZixIfgf+rix2lprA7YqmAAP+8FSNW00Y2jQNMm1Ntfnxdgzd/s7RDYhb74LcXquX3HZSC8QYgrZ6/RQJwgGA91lCd3t7UgJsn/XP/zSKqWr4RuJHUhE0eBkHDNuwPZQzPiHZvIVwPIHyztNGI9Z/eHY0mcgrgDtEc0wRVtJLbbDRPCXmeOoNooaqUkihkwAMJ2XAv9ky+hFdKFTSI/UqjZOG1q9X4x8AhZYhMrCzL8/8XyxnyGYCquLrMnE47htqcx04rl4hcaD7jGJZ+tTOJzMuERnrjBgXmJZHRzqndswUL4E0PIvY/y6xMFTrw4SlxBp8fqg2Tg6c+e0PNv7loH9VMCwTbld11yUPqmTQEkuH+RmdWeNAeWYfLDH9WFEQSW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-credentials
      namespace: phase-1
